### ISSUE TITLE
No Airline operator flags & Aircraft silhouettes

### ISSUE THREAD

**Issue by SA7BNT** [mypiaware/virtual-radar-server-installation#1]
Hallo,

thanks for the nice script. But im running in at an issue.
The Airline operator flags & Aircraft silhouettes will not showing up.
Is there something i missed?? At the installation i typed Y to install them. 
All the bmp are in the right folder. 
<img width="1299" alt="Bildschirmfoto 2019-11-02 um 20 16 35" src="https://user-images.githubusercontent.com/35367117/68075839-cd79ec80-fdad-11e9-9f88-f9e3abaa4561.png">

That is my system.
<img width="457" alt="Bildschirmfoto 2019-11-02 um 20 09 33" src="https://user-images.githubusercontent.com/35367117/68075825-93a8e600-fdad-11e9-966e-5f4b13b6f536.png">

**Comment by mypiaware** [comment]
Thank you very much for your feedback!  I am sorry the airline operator flags & aircraft silhouettes are not appearing for you.

Today, I ran my script on a completely clean installation of Lubuntu just to check if there is an error in my code.  I started VRS, and immediately I was able to see both airline operator flags & aircraft silhouettes.

You mentioned the BMP files have been downloaded to the correct folders.  So, that is good.

Looking at your screenshot of VRS, I see that you highlighted a Finnair A321 plane.  The sample files you downloaded should have included the airline operator flag for Finnair (FIN.bmp) and the aircraft silhouette for the A321 (A321.bmp).  So, I am confused as to why you would not see them in your VRS.

The only thing I can think to check is to make sure the correct paths for the airline operator flags & aircraft silhouettes have been set in the VRS settings.  My installation script was supposed to automatically fill these paths for you.  So, let us make sure my script did it correctly...

Bring up the VRS options.  The first thing you should see in the Options window is the "Data Sources" settings.  On the right, under "Data Sources", make sure the paths for "Flags folder" and "Silhouettes folder" are correct.  Here is an example from my Raspberry Pi setup...

![DataSourcesScreenshot](https://user-images.githubusercontent.com/40304323/68091810-7ed25e00-fe52-11e9-9455-59d499f74876.png)

**Comment by SA7BNT** [comment]
Hallo, thanks for your replay. 
I tested your script on a pi and there all runs 100%, so i wonder where the issue is.
It seems that the issue is somewere in Mono. 
[https://forum.virtualradarserver.co.uk/viewtopic.php?f=7&t=1957](url) 
So i will investigate a little bit more, and let you know.

Best from Sweden

Edit: Was switching to Debian 9 now we are online again.
