### ISSUE TITLE
Silhouettes not downloading - Kinetic Website down.

### ISSUE THREAD

**Issue by rikgale** [mypiaware/virtual-radar-server-installation#11]
Hello

I just got the following error msg while installing VRS preview 3.0.0.0 on a feeder 

```
-2022-02-04 13:43:50--http://www.kinetic.co.uk/repo/SilhouettesLogos.zip
Resolving www.kinetic.co.uk (www.kinetic.co.uk)... 62.30.206.164
Connecting to www.kinetic.co.uk (www.kinetic.co.uk)|62.30.206.164|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-04 13:43:50 ERROR 404: Not Found
Failed to download SilhouettesLogos.zip!
```

I went to the address given and got a 404 error. Kinetic website appears to be down, again.

Would you consider using my silhouettes in your script? The silhouettes zip is available in my GitHub repo [https://github.com/rikgale/VRSOperatorFlags](https://github.com/rikgale/VRSOperatorFlags) The silhouettes can be seen in the gallery on radar spotting [https://radarspotting.com/forum/index.php?action=gallery;cat=6](https://radarspotting.com/forum/index.php?action=gallery;cat=6) or in action on my website [https://www.cornwallvrs.duckdns.org/VirtualRadar/desktop.html](https://www.cornwallvrs.duckdns.org/VirtualRadar/desktop.html) or on my PlaneAlert page [https://www.cornwallvrs.duckdns.org/planealert/](https://www.cornwallvrs.duckdns.org/planealert/) 

These silhouettes are regularly updated and maintained. My long-term aim to represent every ICAO type code. Most common silhouettes are completed and it is the odd and the rare ones left to do. The old kinetic silhouettes are not complete and are no longer maintained or updated.

Also Dual View (DV) silhouettes are available in the same repo if you wanted to bring some options to the users of this script. They have been rather popular amongst the users of the radarspotting forum.

To further bring variety I will soon be doing the silhouettes / DV silhouettes with a transparent background, these also work well in VRS for those that want a white BG for their silhouettes.

I hope you will consider this?

**Comment by mypiaware** [comment]
Hello and thank you for your interest in my script!

The SilhouettesLogos.zip file from Kinetic's website is available again.  I am just thinking it was briefly down at the time you tried to download it.

I did take a quick look at your silhouette images and was impressed.  I am glad to see that you have the same light blue background color used by many of the airline logo images.  I created my own 400 airline logo images and used the same light blue color in the background.  (The airline logo images downloaded by my script are not mine.  Mine are kept private.)  I will take a look further into your silhouettes and consider changing my script to use your images.  It may be a few days to a week before I can get to this.  But, either way, I will let you know.

Thanks again!

**Comment by rikgale** [comment]
Hello.
Thanks for getting back to me on this and taking the time to have a look at my silhouettes. The kinetic silhouettes were originally made by Ian K whos silhouettes are also listed on the woodair.net website that you get your airline logos from. His website is still up and available but he has not made a silhouette since mid-2020.

Feel free to have a look at some of the other Zips in my repo to see if they may be of any use to you...
Thanks.

**Comment by mypiaware** [comment]
I made the update now to my script to use your silhouettes.  They look very good!

The dual view idea is very interesting as well.  I will probably stick with the single view, though, in my script.  (FYI - Check "C08T.bmp".  Looks like a dual view sneaked in with your regular silhouettes.)

Thanks again!

**Comment by rikgale** [comment]
Ah great. I shall look forward to installing on the next feeder I make. I have updated C08T - thanks for spotting. The zip in the repo has been updated. If you spot anything else please do let me know.
