### ISSUE TITLE
How can i edit the receiver ip?

### ISSUE THREAD

**Issue by hi1213345446231** [mypiaware/virtual-radar-server-installation#12]
how can i edit the reciever ip i entered?

**Comment by mypiaware** [comment]
Hello, you may edit the receiver by starting VRS and making the changes in VRS settings by doing the following:

- Run the `vrs -gui` command to start VRS with a GUI.
- At the top of the VRS window, select "Tools" and then "Options...".
- With the "Options" window now open, locate the "Receivers" section on the left side.
- Under the "Receivers" section, click the receiver needing to be edited.
- On the right side, make edits to the receiver.  (In your case, you will edit the "Address" field to change the IP address.)
- Click the "OK" button at the bottom to save your edits.

I hope this helps.
