### ISSUE TITLE
Failed to load module "pk-gtk-module"

### ISSUE THREAD

**Issue by blufox337** [mypiaware/virtual-radar-server-installation#14]
Your suggested solution to fix the problem did not
work for me.  Here is what did work:

  dnf install gtk2-devel gtk3-devel gtk4-devel

**Comment by mypiaware** [comment]
What operating system are you using?

**Comment by mypiaware** [comment]
Unfortunately, I was never informed of the operating system.  I will close this issue.  This is also not much of a concern as I do not believe this error affects the functionality of VRS.
