### ISSUE TITLE
The server occasionally stops working.

### ISSUE THREAD

**Issue by SA7BNT** [mypiaware/virtual-radar-server-installation#18]
Recently, the VRS has been stopping from time to time. I see this message in the log. My question is: Can I simply run the installation script again without losing my configured receivers, or is there a better solution to fix this issue?
<img width="1435" alt="Bildschirmfoto 2024-11-13 um 19 10 57" src="https://github.com/user-attachments/assets/177decf1-6515-489e-b019-b155431eece8">
Best Tim

**Comment by mypiaware** [comment]
Hello Tim,

I am sorry to hear that you are having difficulties with your VRS stability.  I will say that I have been using VRS on multiple Raspberry Pi's for over 5 years, and they have all been stable for me.  So, VRS can run stable if the device is reliable.  I cannot even begin to decipher the errors from your screenshot.

Yes, you can run the script again to reinstall VRS, and it will keep such settings as your location and receivers.  Please see these notes here (it says it is for updating VRS, but it still applies to a re-installation):

https://github.com/mypiaware/virtual-radar-server-installation?tab=readme-ov-file#how-to-perform-an-update

You may also want to take note that this installation also provides a watchdog script that will monitor the status of your VRS and start it again if it detects that it has stopped for any reason.  Please see these notes here:

https://github.com/mypiaware/virtual-radar-server-installation?tab=readme-ov-file#watchdog-script

I hope this helps.

**Comment by SA7BNT** [comment]
Thank you for your response. 

I have now run the installation script and installed version 2.4.4 along with the libpng fix. I have also added the watchdog to the crontab. 
One final question: I don’t always see all the flags in the tracking aircraft list. Is there a fix for this or an alternative source?
<img width="618" alt="Bildschirmfoto 2024-11-15 um 07 41 07" src="https://github.com/user-attachments/assets/cae85b3d-3f88-445b-8241-3b9928ad4311">

Best Tim

Edit: but still getting problem.
<img width="1153" alt="Bildschirmfoto 2024-11-15 um 15 29 46" src="https://github.com/user-attachments/assets/b34a72ab-1a37-4d67-85c8-dd7c3d9596bb">

And Watchdog is doing nothing 
 
<img width="824" alt="Bildschirmfoto 2024-11-15 um 16 32 38" src="https://github.com/user-attachments/assets/ddb5ea2f-7f0f-422a-b29c-1b075a8ba13e">

**Comment by mypiaware** [comment]
The `LOGO.zip` file containing airline flags that gets downloaded by my script does not have every known airline flag.  So, there will be some aircraft without airline flags.  You can always try to search for another source of airline flags.  I created my own to add to the ones from the `LOGO.zip` file.

I do not know the reason why your VRS keeps crashing.  Sorry, but I do not think I am going to be able to debug this.  (I am not the creator of VRS.)  I would focus on your system.  If possible, reinstall the OS, make sure it is completely updated, and try reinstalling VRS again.

The `vrs_watchdog.log` that you provided is showing that the watchdog script is doing exactly what it is supposed to be doing.  If it detects that VRS is not running, the watchdog will start it again.  The log shows that it is doing just that.  In theory, you can just leave your VRS as it is now.  Yes, VRS will occasionally crash, but VRS will start back up again from the watchdog script.  Of course, actually fixing the crashing issue would be a much better alternative.
