### ISSUE TITLE
Remove everything in this installation?

### ISSUE THREAD

**Issue by Augusto271** [mypiaware/virtual-radar-server-installation#7]
How do I remove everything from this installation to fresh install it again?

**Comment by mypiaware** [comment]
Hello.  It should be fairly easy to completely remove the installation.  I do not know if you want to remove only the VRS files, or if you want to also remove Mono as well.  There are two parts to removing both VRS & Mono.  Mono is the underlying program that allows VRS to run on Linux.

To completely remove all of the VRS files, execute the following two commands.  I am making an assumption you have not modified my script in any way, and you are using the default directory structure given by my script.

```
rm -rf ~/VirtualRadarServer
rm -rf ~/.local/share/VirtualRadar
```

If you are wanting to also remove Mono, I would need to know your operating system.  But, I will say that for Debian flavors (Debian, Raspberry Pi OS, Ubuntu, etc.), the following command will remove Mono:

```
sudo apt purge --auto-remove mono-runtime
```

**Comment by Augusto271** [comment]
Thank you!
