### ISSUE TITLE
Silhouettes and Flags not showing on external IP address

### ISSUE THREAD

**Issue by Augusto271** [mypiaware/virtual-radar-server-installation#8]
When I access the VRS via external IP address no silhouettes and flags are shown

**Comment by Augusto271** [comment]
The plane icons show normally and using via the local ip it shows the flags and silhouettes

**Comment by mypiaware** [comment]
I can certainly try to help, but I will need more information.  For example:

- What operating system are you using?
- Are you using the stable or preview version of VRS?
- What is your setup? (How are you allowing the outside world to access your server?)
- Can you show me your external URL?

If there is anything else you believe that will be helpful to me, please let me know.

**Comment by Augusto271** [comment]
Hello thank you for helping!

- What operating system are you using?
Ubuntu 20.04.1 LTS

- Are you using the stable or preview version of VRS?
Preview

- What is your setup? (How are you allowing the outside world to access your server?)
Yes I have the server port opened in my router.

**Comment by mypiaware** [comment]
OK, try running the installation script again.  But, this time, choose the stable version.  You will probably have a problem with plane icons not showing on your Ubuntu system.  But, for now, that is OK.  I am just interested in seeing if it makes a difference with the silhouettes and flags.  The nice thing about doing this experiment is that this would be the only change in your setup.  Everything else should be the same.

If you want, before you run the script again, you can do the instructions I gave to you in the other issue you opened to clean things up first.  Let me know if the stable version makes a difference.  I do not have much experience with using the preview version.  My own public VRS setup uses the stable version on a Raspberry Pi and works quite well.

**Comment by mypiaware** [comment]
I did my own experiment just now.

I used an extra Raspberry Pi laying around and used my own script to install the preview version.  I did nothing extra or special for the installation.  I let the script do all the work.  I then opened up the port for this extra Raspberry Pi on my router.  I checked the VRS page using my phone (disconnected from my WiFi to ensure that I am off my local network).  Both the silhouettes and flags appeared fine in both the desktop (VirtualRadar/desktop.html) and mobile (VirtualRadar/mobile.html) pages.

So, the silhouettes and flags on the preview version work fine for me when viewed from an external device.  Unfortunately, I do not know what could be causing this issue you are having.

**Comment by Augusto271** [comment]
Hello, I've tried with the stable and unstable version and the problem persists... If I find the reason I'll let you know

**Comment by Augusto271** [comment]
<img width="281" alt="Screenshot 2021-01-18 at 11 55 43" src="https://user-images.githubusercontent.com/32555389/105638392-a5731f00-5e72-11eb-863a-c995af2f4840.png">
 Looks like this

**Comment by mypiaware** [comment]
How about trying a minimal installation of VRS just to see what happens?

**1. You should already have Mono installed.  But if you do not, then run the following:**
```
sudo apt update
sudo apt install -y mono-complete
```

**2. To be safe, remove your possibly already existing VRS installation:**
```
rm -rf ~/VirtualRadarServer
rm -rf ~/.local/share/VirtualRadar
```

**3. Create a temporary VRS setup:**
```
mkdir -p ~/TestVRS/Installation ~/TestVRS/Logos ~/TestVRS/Silhouettes

wget -P ~/TestVRS http://www.virtualradarserver.co.uk/Files/VirtualRadar.tar.gz
wget -P ~/TestVRS http://www.virtualradarserver.co.uk/Files/VirtualRadar.exe.config.tar.gz
wget -P ~/TestVRS http://www.woodair.net/SBS/Download/LOGO.zip
wget -P ~/TestVRS http://www.kinetic.co.uk/repo/SilhouettesLogos.zip

tar -xf ~/TestVRS/VirtualRadar.tar.gz -C ~/TestVRS/Installation
tar -xf ~/TestVRS/VirtualRadar.exe.config.tar.gz -C ~/TestVRS/Installation
unzip -j -o -qq ~/TestVRS/LOGO.zip "[A-Z][A-Z][A-Z].bmp" -d ~/TestVRS/Logos
unzip -j -o -qq ~/TestVRS/SilhouettesLogos.zip "*.bmp" -d ~/TestVRS/Silhouettes
```
**4.  Start VRS:**
```
mono ~/TestVRS/Installation/VirtualRadar.exe
```

**5.  Make the following edits by clicking Tools -> Options in VRS (note: do not worry about any other setting):**

* Data Sources (on the left)
   * Flags folder: (click button to navigate to the Logos directory)
   * Silhouettes folder:  (click button to navigate to the Silhouettes directory)

* Receivers (on the left)
   * Edit the following parameters of the one existing receiver to receive the ADS-B data from your receiver.
      * Format
      * Address
      * Port

Now, on your local machine, bring up the VRS webpage to verify you are seeing the flags and silhouettes.  You said you have not had a problem seeing these images on your local machine.  So, you should be able to see these just fine on your local machine.  After confirming you can see the images on your local machine, try to view the images from an external device.  Remember, on this temporary installation, the port number will be `8080`.

When you are finished with this temporary installation and are wanting to remove it, just run:
```
rm -rf ~/TestVRS
rm -rf ~/.local/share/VirtualRadar
```

**Comment by Augusto271** [comment]
Ok I found out what it was... It was my DNS server blocking it.
I changed it to google's dns and now it works! Thank you for your pacience

**Comment by mypiaware** [comment]
:+1: Great!  I am glad you found out what the problem was.  I never heard of this DNS-blocking issue before.  Good thing to remember.
